global:
  scrape_interval:     15s

  external_labels:
    monitor: 'payara-firehose'

scrape_configs:
  - job_name: 'payara-firehose'
    scrape_interval: 5s
    metrics_path: '/firehose/resources/metrics'
    static_configs:
      - targets: ['payara-firehose:8090']