version: '3.0'
services:
  elasticsearch:
    image: airhacks/elasticsearch
    ports:
    - "9200:9200"
  kibana-elasticsearch:
    image: airhacks/kibana-elasticsearch
    ports:
    - "5601:5601"
    links:
    - elasticsearch

