FROM airhacks/kibana
LABEL maintainer="Adam Bien, adam-bien.com" description="Kibana with elasticsearch configuration"
RUN echo -e 'elasticsearch.url: "http://elasticsearch:9200"' >> ${INSTALL_DIR}/config/kibana.yml

