global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'prometheus-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['service:8080']