version: '3.0'
services:
  payara-firehose:
    image: airhacks/payara-firehose
    ports:
    - "8080:8080"
    - "4848:4848"    
  prometheus-firehose:
    image: airhacks/prometheus-firehose
    ports:
    - "9090:9090"
    links:
    - payara-firehose
  grafana:
    image: airhacks/grafana
    ports:
    - "3000:3000"
    links:
    - prometheus-firehose
  configuration-loader:
    image: airhacks/payara-monitoring-loader
    links:
    - payara-firehose

