FROM airhacks/openliberty-kernel
LABEL maintainer="Tobias N. Sasse, @tnsasse and Adam Bien, adam-bien.com" description="OpenLiberty Java EE 7 WebProfile"

ENV DEPLOYMENT_DIR /config/dropins/
COPY server.xml /config/
